name: Marriage
version: 1.2.4
main: com.lenis0012.bukkit.marriage.Marriage
author: lenis0012, GoldMorphiN (перевод)
description: Плагин отношений в Minecraft.
dev-url: http://dev.bukkit.org/bukkit-mods/marriage-reloaded/
softdepend: [Vault]
commands:
  marry:
    description: Основная команда Marriage.
    usage: /marry <args>
permissions:
  marry.*:
    description: Разрешает все команды плагина
    children:
      marry.admin:
        description: Позволяет все админ-команды плагина
        children:
          marry.reload:
            description: Позволяет перезагружать конфиг файл плагина
          marry.priest:
            description: Позволяет игроку женить двух других игроков
          marry.chatspy:
            description: Позволет (chatspy) сообщения от других игроков 
      marry.default:
        description: Позволяет все команды по-умолчанию
        children:
          marry.marry:
            description: Позволяет женится/выходить замуж
          marry.chat:
            description: Позволяет чат, с Вашим партнёром
          marry.tp:
            description: Позволяет телепортироваться к Вашему партнёру
          marry.home:
            description: Позволяет телепортироваться домой, если таковой установлен
          marry.sethome:
            description: Позволяет установить точку совместного дома
          marry.gift:
            description: Позволяет дарить подарки Вашему супругу
          marry.chat:
            description: Позволяет чат с Вашим партнёром
          marry.child:
            description: Allows everything with children in marriage. //понятие не имею, что это
          marry.seend:
            description: Позволяет видеть последний заход на сервер Вашего супруга